In [30]:
# Create a numpy array of int, characters, float and find their shapes

import numpy as np

# Create a numpy array of int
arr_int = np.array([1, 2, 3, 4,9,10,11,12])
arr_char = np.array(['a', 'b', 'c', 'd', 'e', 'f'])
arr_float = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

#find their shapes
print("Shape of arr_int is: ", arr_int.shape)
print("Shape of arr_char is: ", arr_char.shape)
print("Shape of arr_float is: ", arr_float.shape)

Shape of arr_int is:  (8,)
Shape of arr_char is:  (6,)
Shape of arr_float is:  (5,)


In [31]:
# Create a zeros, empty, identity , eye and a full array
arr_zeros = np.zeros((3, 3))
arr_empty = np.empty((3, 3))
arr_identity = np.identity(3)
arr_eye = np.eye(3)
arr_full = np.full((3, 3), 5)

# Print the arrays
print("arr_zeros is: ", arr_zeros)
print("arr_empty is: ", arr_empty)
print("arr_identity is: ", arr_identity)
print("arr_eye is: ", arr_eye)
print("arr_full is: ", arr_full)
    

arr_zeros is:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arr_empty is:  [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
arr_identity is:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr_eye is:  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
arr_full is:  [[5 5 5]
 [5 5 5]
 [5 5 5]]


In [32]:
# Declare an array having the datatype of object.
arr_obj = np.array([1, 2, 3, 4, 5], dtype=object)
print("arr_obj is: ", arr_obj)

print("\nYes Possible")

arr_obj is:  [1 2 3 4 5]

Yes Possible


In [33]:
# Create an array having 5 equally spaced numbers ranging from 5 to 15
arr = np.linspace(5, 15, 5)
print("arr is: ", arr)


arr is:  [ 5.   7.5 10.  12.5 15. ]


In [34]:
# Create a numpy array ranging from 1 to 100.
arr = np.arange(1, 101)
print("arr is: ", arr)

arr is:  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [35]:
# Reshape the above array into (100,15). Is it possible?
# arr = np.arange(1, 101).reshape(100, 15)
# print("arr is: ", arr)

print ("\n No Not Possible")


 No Not Possible


In [36]:
# Reshape the array into (100,10).
# arr = np.arange(1, 101).reshape(100, 10) // This is not possible
arr = np.arange(1, 101).reshape(10, 10) # This is possible
print("arr is: ", arr)

arr is:  [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [40]:
# Flatten and ravel the reshaped array. What is the difference?
arr_flatten = arr.flatten()
arr_ravel = arr.ravel()
print("arr_flatten is: ", arr_flatten)
print("arr_ravel is: ", arr_ravel)

print("\nThe difference between flatten and ravel is that flatten returns a copy of the array while ravel returns a view of the array")

    

arr_flatten is:  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
arr_ravel is:  [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]

The difference between flatten and ravel is that flatten returns a copy of the array while ravel returns a view of the array


In [41]:
# Take an array [[1 2 3] [4 5 6] [ 7 8 9]]. Sum it along 0 and 1 axis
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("arr is: ", arr)
print("Sum along 0 axis is: ", arr.sum(axis=0))
print("Sum along 1 axis is: ", arr.sum(axis=1))

        

arr is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum along 0 axis is:  [12 15 18]
Sum along 1 axis is:  [ 6 15 24]


In [42]:
# Find the number of bytes used by your array
print("Number of bytes used by arr is: ", arr.nbytes)
    

Number of bytes used by arr is:  72


In [43]:
# Find the maximum and minimum values in a 1D array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("arr is: ", arr)

print("Maximum value in arr is: ", arr.max())
print("Minimum value in arr is: ", arr.min())

arr is:  [1 2 3 4 5 6 7 8 9]
Maximum value in arr is:  9
Minimum value in arr is:  1


In [44]:
# Find the maximum and minimum values in 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("arr is: ", arr)

print("Maximum value in arr is: ", arr.max())
print("Minimum value in arr is: ", arr.min())


arr is:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Maximum value in arr is:  9
Minimum value in arr is:  1


In [46]:
# Sort an array
arr = np.array([1,4,3, 2, 7, 8, 9])
print("arr is: ", arr)

arr.sort()
print("arr after sorting is: ", arr)


arr is:  [1 4 3 2 7 8 9]
arr after sorting is:  [1 2 3 4 7 8 9]


In [49]:
# Is * and mul the same as dot product for numpy arrays and matrices? Check.
arr1 = np.array([1, 2, 3])  
arr2 = np.array([4, 5, 6])
print("arr1 is: ", arr1)
print("arr2 is: ", arr2)

print("arr1 * arr2 is: ", arr1 * arr2)
print("arr1.dot(arr2) is: ", arr1.dot(arr2))



arr1 is:  [1 2 3]
arr2 is:  [4 5 6]
arr1 * arr2 is:  [ 4 10 18]
arr1.dot(arr2) is:  32


In [50]:
# Take the square root and norm of an array.
arr = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
print("arr is: ", arr)

print("Square root of arr is: ", np.sqrt(arr))
print("Norm of arr is: ", np.linalg.norm(arr))

        

arr is:  [  1   4   9  16  25  36  49  64  81 100]
Square root of arr is:  [ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
Norm of arr is:  159.16343801262903


In [51]:
# Find the std, non-zero, zero values and mean of an array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print("arr is: ", arr)

print("Standard deviation of arr is: ", np.std(arr))
print("Non-zero values in arr is: ", np.count_nonzero(arr))
print("Zero values in arr is: ", np.count_nonzero(arr == 0))
print("Mean of arr is: ", np.mean(arr))
    

arr is:  [1 2 3 4 5 6 7 8 9]
Standard deviation of arr is:  2.581988897471611
Non-zero values in arr is:  9
Zero values in arr is:  0
Mean of arr is:  5.0


In [52]:
# Convert some angles to radians and vice versa.
arr = np.array([0, 30, 45, 60, 90])
print("arr is: ", arr)

print("arr in radians is: ", np.radians(arr))
print("arr in degrees is: ", np.degrees(arr))

        

arr is:  [ 0 30 45 60 90]
arr in radians is:  [0.         0.52359878 0.78539816 1.04719755 1.57079633]
arr in degrees is:  [   0.         1718.87338539 2578.31007809 3437.74677078 5156.62015618]


In [54]:
# Save and load some of your arrays
arr = np.array([1, 4, 2, 6, 7, 8, 9])
print("arr is: ", arr)

np.save("arr", arr)
arr_load = np.load("arr.npy")
print("arr_load is: ", arr_load)



arr is:  [1 4 2 6 7 8 9]
arr_load is:  [1 4 2 6 7 8 9]


In [56]:
# Calculate the mean, std, var, max, min, of an array with shape (3,3,12,3) containing floats drawn from a normal distribution with mean 21 and sigma 4.5. see the np.random.normal.
arr = np.random.normal(21, 4.5, (3, 3, 12, 3))
print("arr is: ", arr)
print()
print("Mean of arr is: ", np.mean(arr))
print("Standard deviation of arr is: ", np.std(arr))
print("Variance of arr is: ", np.var(arr))
print("Maximum value in arr is: ", np.max(arr))
print("Minimum value in arr is: ", np.min(arr))



arr is:  [[[[20.81815232 23.13976344 14.65254511]
   [19.34202866 21.84830666 21.48531214]
   [19.03435503 20.17391937 17.45621474]
   [27.20991933 16.385663   20.9138636 ]
   [20.55449004 25.74806582 18.38878253]
   [11.60846553 25.61759176 22.72759192]
   [24.98014974 18.27892724 19.05689472]
   [17.64232455 17.68050536 16.67800387]
   [22.21227862 19.54366264 24.37326456]
   [20.99558877 24.35770317 19.55339463]
   [16.25842964 23.37258585 29.55705894]
   [24.31915783 26.0529209  23.49105659]]

  [[24.63028161 18.94559643 26.00675595]
   [11.8690672  17.2717762  25.34476047]
   [22.13305925 27.42873448 18.72036585]
   [18.20774246 21.66150929 18.51481914]
   [22.26316677 18.15047131 16.44402306]
   [21.2439899  26.85679753 19.7802412 ]
   [27.39798311 24.98525013 19.20598622]
   [30.78223171 18.35584993 22.51151202]
   [12.9215074  19.86050304 20.17039071]
   [17.25588432 20.95648893 14.97301927]
   [19.54555736 24.17289578 11.31976237]
   [25.78979346 13.01023203 21.6451614 ]]

  [